apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: helloworldserial # The name of the function instance
  namespace: default
spec:
  template:
    spec:
      containerConcurrency: 1
      containers:
        - image: crccheck/hello-world:latest # Stub image. See https://github.com/ease-lab/vhive/issues/68
          ports:
            - name: h2c # For GRPC support
              containerPort: 50051
          env:
            - name: GUEST_PORT # Port on which the firecracker-containerd container is accepting requests
              value: "50051"
            - name: GUEST_IMAGE # Container image to use for firecracker-containerd container
              value: "ustiugov/helloworld:var_workload"
