dist: bionic
language: go

go:
#  - 1.14.x
  - 1.13.x

env:
  - GO111MODULE=on

#install:
#  - make deps
before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0

script:
  - go build ./... 
  - golangci-lint run ./...
  - go test -v github.com/ustiugov/fccd-orchestrator/misc
#  # "make" must be happening before "make lint" to download dependencies
#  - make
#  - make lint
#  - make test
