dist: bionic
language: go

sudo: required

go:
  - 1.14.x

env:
  global:
  - GO111MODULE=on GOPRIVATE=github.com/ustiugov/fccd-orchestrator
  jobs:
  - TEST=test-subdirs
  - TEST=test
  - TEST=test-man

before_script:
  - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.25.0
  - source ./scripts/setup_ctrd.sh

script:
  - go build ./... 
  - golangci-lint run ./...
  - make $TEST
