# Source: github.com/triggermesh/knative-local-registry
apiVersion: apps/v1 
kind: DaemonSet
metadata:
  name: registry-etc-hosts-update
  namespace: registry
spec:
  selector:
    matchLabels:
      app: registry-etc-hosts-update
  template:
    metadata:
      labels:
        app: registry-etc-hosts-update
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      initContainers:
      - name: update
        image: debian:stretch-slim
        volumeMounts:
        - name: etchosts
          mountPath: /host-etc/hosts
          readOnly: false
        env:
        - name: REGISTRY_SERVICE_HOSTS
          value: >-
            docker-registry.registry.svc.cluster.local
        command:
        - bash
        - -ce
        - |
          NL=$'\n'
          HOSTS="$(cat /host-etc/hosts)"
          for H in $REGISTRY_SERVICE_HOSTS; do
            ent=$(getent hosts $H);
            [ -z "$ent" ] && echo "Failed to get hosts entry for $H" && exit 1;
            echo "$HOSTS" | grep " $H"  || HOSTS="$HOSTS$NL$ent";
            echo "$HOSTS" | grep "$ent" || HOSTS=$(echo "$HOSTS" | sed "s|.* $H|$ent|");
          done;
          echo "$HOSTS" | diff -u /host-etc/hosts - || echo "$HOSTS" > /host-etc/hosts
          echo "Done."
      containers:
      - name: init-container-did-the-work
        image: gcr.io/google_containers/pause:3.1@sha256:f78411e19d84a252e53bff71a4407a5686c46983a2c2eeed83929b888179acea
      terminationGracePeriodSeconds: 30
      volumes:
      - name: etchosts
        hostPath:
          path: /etc/hosts
          