apiVersion: "power.intel.com/v1"
kind: PowerConfig
metadata:
  name: power-config
  namespace: intel-power
spec:
  # Add labels here for the Nodes you want the PowerNodeAgent to be applied to
  powerNodeSelector:
    kubernetes.io/hostname: node-2.power-manager.ntu-cloud-pg0.utah.cloudlab.us
  # Add wanted PowerProfiles here; valid entries are as follows: performance, balance-performance, balance-power
  powerProfiles:
    - "performance"