name: Check if the docker images build successfully

on: 
  workflow_dispatch:
  schedule:
    - cron: '0 9 * * 1'


jobs:
  function_images:
    name: Build function docker images
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        image: [grpc, helloworld, chameleon, pyaes, image_rotate_s3, lr_serving, json_serdes_s3, cnn_serving, rnn_serving, lr_training_s3, video_processing_s3, springboot, tests/save_load_minio]
    steps:
    - uses: actions/checkout@v5
      with:
        ref: main
    - name: docker build images
      # Consecutive COPY commands in Dockerfile fail on github runners
      # Added "DOCKER_BUILDKIT=1" as a temporary fix
      # more discussion on the same issue:
      # https://github.com/moby/moby/issues/37965
      # https://github.community/t/attempting-to-build-docker-image-with-copy-from-on-actions/16715
      # https://stackoverflow.com/questions/51115856/docker-failed-to-export-image-failed-to-create-image-failed-to-get-layer
      run: |
        DOCKER_BUILDKIT=1 docker build ./function-images/${{ matrix.image }}
  integ_test_image:
    name: Build integration test docker images
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        image: [github_runner, github_runner_cri, cri_dev_env]
    steps:
    - uses: actions/checkout@v5
    - name: Handle LFS Caching
      uses: ./.github/actions/lfs-cache
      with:
        lfs_enabled: 'true'
        ref: main
    - name: docker build images
      run: |
        DOCKER_BUILDKIT=1 docker build --file ./scripts/github_runner/Dockerfile.${{ matrix.image }} .
