name: Function Composition Bench

on:
  workflow_run:
    workflows: ["Function Composition Push"]
    branches: [main]
    types: 
      - completed
  
env:
  GOOS: linux
  GO111MODULE: on
  VHIVE_GOLANG_VERSION: golang:1.16.4-alpine3.13

jobs:
  bench-docker-compose-serving:
    name: Serving uBenchmark (docker-compose)
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
    steps:
    - uses: actions/checkout@v2

    - name: Setup grpcurl
      run: |
        wget -qO- https://github.com/fullstorydev/grpcurl/releases/download/v1.8.1/grpcurl_1.8.1_linux_x86_64.tar.gz | sudo tar -C /usr/bin/ -xz grpcurl

    - name: start multi-container program with docker-compose
      run: |
        cd ./function-images/tests/chained-function-serving/
        docker-compose up &> log_file &
        sleep 15s
    - name: invoke the chain
      run: |
        grpcurl -plaintext localhost:3031 helloworld.Greeter.SayHello
    - name: show docker-compose log
      run: cat  ./function-images/tests/chained-function-serving/log_file
        
  bench-serving:
    name: Serving uBenchmark (Knative)
    env:
        GITHUB_RUN_ID: ${{ github.run_id }}
        LOGPATH: /tmp/uBench-logs/${{ github.run_id }}
        GOCACHE: /root/tmp/gocache
        GOPATH: /root/tmp/gopath
    runs-on: [self-hosted, cri]
    strategy:
      fail-fast: false
    steps:

    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.15

    - name: Setup LOGPATH
      run: |
        mkdir -p /tmp/uBench-logs/${{ github.run_id }}

    - name: Host Info
      run: |
        echo $HOSTNAME
        echo $GITHUB_RUN_ID
        echo $LOGPATH

    - uses: actions/checkout@v2

    - name: Start containerd
      run: sudo containerd 1>$LOGPATH/uBench.out 2>$LOGPATH/uBench.err &

    - name: Start one-node cluster
      run : |
        ./scripts/cluster/create_one_node_cluster.sh stock-only && sleep 2m

    - name: Start consumer
      run: KUBECONFIG=/etc/kubernetes/admin.conf kn service apply -f ./function-images/tests/chained-function-serving/service-consumer.yaml && sleep 30s

    - name: Start producer
      run: KUBECONFIG=/etc/kubernetes/admin.conf kn service apply -f ./function-images/tests/chained-function-serving/service-producer.yaml && sleep 30s

    - name: Run invoker client
      run: |
        echo "producer.default.192.168.1.240.sslip.io" > urls.txt
        cd ./examples/invoker
        go build client.go
        cd ../..
        ./examples/invoker/client
    - name: Archive log artifacts
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: /tmp/uBench-logs/${{ github.run_id }}

    - name: Cleaning
      if: ${{ always() }}
      run: ./scripts/github_runner/clean_cri_runner.sh stock-only

  bench-eventing:
    name: Eventing uBenchmark (Knative)
    env:
        GITHUB_RUN_ID: ${{ github.run_id }}
        LOGPATH: /tmp/uBench-logs/${{ github.run_id }}
        GOCACHE: /root/tmp/gocache
        GOPATH: /root/tmp/gopath
    runs-on: [self-hosted, cri]
    strategy:
      fail-fast: false
    steps:
    - name: Set up Golang
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Setup LOGPATH
      run: |
        mkdir -p /tmp/uBench-logs/${{ github.run_id }}

    - name: Host Info
      run: |
        echo $HOSTNAME
        echo $GITHUB_RUN_ID
        echo $LOGPATH

    - uses: actions/checkout@v2

    - name: Start containerd
      run: sudo containerd 1>$LOGPATH/containerd.out 2>$LOGPATH/containerd.err &

    - name: Start one-node cluster
      run : |
        ./scripts/cluster/create_one_node_cluster.sh stock-only && sleep 2m

    - name: Start consumer and producer
      run: KUBECONFIG=/etc/kubernetes/admin.conf ./function-images/tests/chained-function-eventing/manifests/apply.sh && sleep 30s

    - name: Describe
      run: |
        KUBECONFIG=/etc/kubernetes/admin.conf kubectl get -n chained-functions-eventing broker
        KUBECONFIG=/etc/kubernetes/admin.conf kubectl get -n chained-functions-eventing sinkbinding
        KUBECONFIG=/etc/kubernetes/admin.conf kubectl get -n chained-functions-eventing ksvc
        KUBECONFIG=/etc/kubernetes/admin.conf kubectl get -n chained-functions-eventing trigger

    - name: Start Experiment
      run: ./bin/tscli 10.96.0.84:80 start ./function-images/tests/chained-function-eventing/tscli.json

    - name: Invoke Thrice
      run: |
        ./bin/grpcurl -d '{\"name\": \"Mert\"}'  -plaintext producer.chained-functions-eventing.192.168.1.240.sslip.io:80 helloworld.Greeter.SayHello
        ./bin/grpcurl -d '{\"name\": \"Bora\"}'  -plaintext producer.chained-functions-eventing.192.168.1.240.sslip.io:80 helloworld.Greeter.SayHello
        ./bin/grpcurl -d '{\"name\": \"Alper\"}' -plaintext producer.chained-functions-eventing.192.168.1.240.sslip.io:80 helloworld.Greeter.SayHello

    - name: Inspect logs
      run: |
        KUBECONFIG=/etc/kubernetes/admin.conf kubectl logs -n chained-functions-eventing -c user-container -l serving.knative.dev/service=producer
        KUBECONFIG=/etc/kubernetes/admin.conf kubectl logs -n chained-functions-eventing -c user-container -l serving.knative.dev/service=consumer

    - name: End Experiment
      run: ./bin/tscli 10.96.0.84:80 end xxx

    - name: Archive log artifacts
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: /tmp/uBench-logs/${{ github.run_id }}

    - name: Delete
      run: KUBECONFIG=/etc/kubernetes/admin.conf ./function-images/tests/chained-function-eventing/manifests/delete.sh

    - name: Cleaning
      if: ${{ always() }}
      run: ./scripts/github_runner/clean_cri_runner.sh stock-only
