name: Linters
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Spellcheck
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v3
    - uses: rojopolis/spellcheck-github-actions@0.30.0
      name: Spellcheck
      with:
        config_path: configs/.spellcheck.yml
  commitlint:
    name: Commitlint
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      
      - name: Install Commitlint
        run: sudo npm install -g @commitlint/cli

      - name: Lint commits
        run: commitlint 
          --config ${{ github.workspace }}/configs/commitlint.config.js 
          --help-url 'https://stackoverflow.com/a/45974435' 
          --from HEAD~1 --to HEAD 
          --verbose
  markdown-link-check:
    name: LinkCheck
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v3
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          use-quiet-mode: 'yes'
          config-file: 'configs/.linkcheck.json'
