# Copyright (c) 2021 Mert Bora Alper and EASE Lab
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

name: Mare Benchmark

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GOOS: linux
  GO111MODULE: on
  KUBECONFIG: /etc/kubernetes/admin.conf

jobs:
  push:
    name: Push Docker Image
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        path:
          - ""
          - word-count
          - amplab1
        include:
          - path: ""
            tag: driver
          - path: word-count
            tag: word-count
          - path: amplab1
            tag: amplab1
    steps:
      - uses: actions/checkout@v2

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - uses: docker/setup-buildx-action@v1

      - uses: docker/build-push-action@v2
        with:
            file: function-images/tests/mare/${{ matrix.path }}/Dockerfile
            push: true
            tags: vhiveease/mare-${{ matrix.tag }}:volatile

  test:
    name: Test
    needs: push
    env:
        GOCACHE: /root/tmp/gocache
        GOPATH: /root/tmp/gopath
        TMPDIR: /root/tmp
    runs-on: [stock-knative]
    strategy:
      fail-fast: false
      matrix:
        example:
          - word-count
          - amplab1
    steps:
      - name: Setup TMPDIR
        run: mkdir -p $TMPDIR

      - uses: actions/checkout@v2
        with:
          lfs: true

      - name: Checkout LFS objects
        run: git lfs checkout

      - name: Configure AWS credentials using EASE lab account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: us-west-1
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install AWS CLI
        shell: bash
        run: |
          set -x

          if ! command -v aws &> /dev/null
          then
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip -qq awscliv2.zip
            sudo ./aws/install
          fi

      - name: Apply
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY }}
        working-directory: function-images/tests/mare/
        run: |
          set -x

          TAG=${{ matrix.example }} envsubst < worker.yml | kn service apply --wait-timeout 60 --filename /dev/stdin \
            --env AWS_REGION=us-west-1 \
            --env AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
            --env AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
            || { kubectl describe ksvc/worker; exit 1; }

          # driver
          kn service apply --wait-timeout 60 --filename driver.yml \
            --env AWS_REGION=us-west-1 \
            --env AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID" \
            --env AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY" \
            --env WORKER_URL="worker.default.svc.cluster.local:80" \
            --env INTER_HINT="s3://ease-lab-vhive/workspaces/ci/${{ matrix.example }}/" \
            --env OUTPUT_HINT="s3://ease-lab-vhive/workspaces/ci/${{ matrix.example }}/" \
            --env INPUT_LOCATORS=$(aws s3api list-objects --bucket ease-lab-vhive --prefix benchmarks/${{ matrix.example }}/inputs/ | jq -r '.Contents[].Key' | grep '.*.tsv' | sed 's/^/s3:\/\/ease-lab-vhive\//') \
            || { kubectl describe ksvc/driver; exit 1; }

      - name: Test and Verify
        run: |
          set -x

          LOCATOR=$(./bin/grpcurl -max-time 180 -plaintext driver.default.127.0.0.1.nip.io:31080 helloworld.Greeter.SayHello | jq -r '.message')
          aws s3 cp $LOCATOR - | LC_ALL=C sort - | cmp function-images/tests/mare/${{ matrix.example }}/expected-output.tsv -

      - name: Print logs
        if: ${{ always() }}
        run: |
          set -x

          kubectl logs -c user-container -l serving.knative.dev/service=worker
          kubectl logs -c user-container -l serving.knative.dev/service=driver

      - name: Cleaning
        if: ${{ always() }}
        run: |
          kn service delete --all --namespace default --wait

      - name: Clean up S3
        if: ${{ always() }}
        run: |
          aws s3 rm s3://ease-lab-vhive/workspaces/ci/${{ matrix.example }}/ --recursive
